Add form
mumbereh/first-portfolio pull request #4
Opened 2023-03-28 21:05 UTC by mumbereh

I have added the form to my mobile portfolio project. 
Making it complete.

2023-03-28 21:36 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @mumbereh and @Mar12358 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 21:36 UTC, tresorsawasawa commented on index.html
> +                <h2 class="form-header">
- [ ] As required for the project, kindly make sure your Form uses the `action` and `method` attribute to integrate with [formspree service](https://formspree.io/html).
 * `action` value should be similar to `https://formspree.io/f/{form_id}`
 * `method` value equals `POST`

2023-03-28 21:36 UTC, tresorsawasawa commented on index.html
> +                <h2 class="form-header">
- [ ] Once you have fixes the above change, kindly make sure you check the `network` tab in your browser dev tools to confirm that the form is submitted successfully with valid input values. Below is how your application looks after a user has submitted a form:
![Screenshot from 2023-03-28 17-24-29](https://user-images.githubusercontent.com/83042742/228370411-91646f6e-a658-4309-a236-e9ed6f5d53ea.png)

2023-03-28 21:36 UTC, tresorsawasawa commented on index.html
> +                    </li>
- [ ] As required for the project, kindly make sure all your input fields have the `required` attribute to activate the validation on submit. I noticed that you forgot add the `required` attribute in the `textarea` input

2023-03-28 21:36 UTC, tresorsawasawa commented on style.css
> +form p {
- [ ] As required for the project, kindly make sure `Flexbox` is used to layout the elements of your footer section.

2023-03-28 23:05 UTC, vickymarz requested changes
Hi @mumbereh, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 23:05 UTC, vickymarz commented on index.html
> +                        <input type="text" name="email" placeholder="enter your email......"required>
[OPTIONAL]

- Kindly ensure that your email input fields have the correct type attribute i.e email input's `type` equals `email` which is the proper way of declaring an input field 👍🏽

2023-03-28 23:05 UTC, vickymarz commented on index.html
> +                    <li>
- [ ] As suggested by the previous reviewer, kindly make sure Flexbox is used to layout the elements of your contact section and the form itself so as to make the section responsive and also gives you the added advantage of laying out the elements the way you want to improve user experience 👍🏽 .

2023-03-29 07:38 UTC, Olamarx approved these changes
Hi @mumbereh,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>
## Highlights
- Linters passed ✔️ 
- Flexbox ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 07:38 UTC, Olamarx commented on style.css
> +}
Nice one using flex 👍

2023-03-29 07:42 UTC, merged